
- hosts: masters
  user: ubuntu
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    - name: SSH connectivity
      wait_for_connection:

    - name: CloudInit done /var/lib/cloud/instance/boot-finished exists
      raw: while ! test -f /var/lib/cloud/instance/boot-finished; do sleep 5s; done
      retries: 5
      delay: 1

#Install k3s on master
- hosts: masters
  user: ubuntu
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    - name: Install k3s on master
      raw: curl -sfL https://get.k3s.io | sh -
    - name: set masterToken
      command: "cat /var/lib/rancher/k3s/server/node-token"
      register: command_output
    - set_fact:
        master_token={{ command_output.stdout }}
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] }}"
    - name: Print masterToken to console
      ansible.builtin.debug:
        msg: Token is {{ master_token }} and IP is {{groups['masters'][0]}}

#Install k3s on nodes with url,token env-vars
- hosts: nodes
  user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Install curl
      apt:
        name: ["curl"]
        update_cache: yes #apt update
        state: latest
    - name: gimme tha environment
      ansible.builtin.debug:
          msg: Token is {{ master_token }} and IP is {{groups['masters'][0]}}
    - name: Install k3s on nodes with master url and token
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://${k3s_url} K3S_TOKEN=${k3s_token} sh -"
      environment:
        k3s_url: "{{groups['masters'][0]}}:6443"
        k3s_token: "{{ master_token }}"

